// ADD OR EDIT IELTS TOPICS IN THIS FILE.
// Copy one complete topic block, paste it before the closing ]; and edit its text.
// Keep every id unique. Categories are created automatically from this file.

const topics = [
  {
    id: "helpful-person",
    category: "People",
    part2: "Describe a person who has helped you achieve a goal",
    cues: ["who this person is", "what goal you wanted to achieve", "how they helped you", "how you felt about their help"],
    part3: ["Why do people set goals?", "Should parents help children set goals?", "Is teamwork always helpful when pursuing a goal?", "What makes someone a good mentor?"]
  },
  { id: "interesting-place", category: "Places", part2: "Describe an interesting place you would like to visit", cues: ["where it is", "how you learned about it", "what you would do there", "why you find it interesting"], part3: ["Why do people enjoy visiting unfamiliar places?", "How can tourism change a local community?", "Should famous places limit visitor numbers?", "Will virtual travel ever replace physical travel?"] },
  { id: "skill-learned", category: "Experiences", part2: "Describe a useful skill you learned outside school", cues: ["what the skill is", "when and how you learned it", "how difficult it was", "why it is useful to you"], part3: ["Which skills should schools teach?", "Do people learn better alone or with others?", "Why do some adults stop learning new skills?", "How has technology changed the way people learn?"] },
  { id: "object-kept", category: "Things", part2: "Describe an old object that your family has kept for a long time", cues: ["what it is", "where it came from", "how long your family has had it", "why it is important"], part3: ["Why do people keep old objects?", "Are museums still important today?", "What kinds of objects represent a culture?", "Will digital records replace physical keepsakes?"] },
  { id: "nature-place", category: "Nature", part2: "Describe a natural place where you feel relaxed", cues: ["where it is", "what it looks like", "what you do there", "why it helps you relax"], part3: ["Why is access to nature important in cities?", "Who should pay to protect natural areas?", "How can tourism harm the environment?", "Do young people care enough about nature?"] },
  { id: "good-news", category: "Experiences", part2: "Describe a piece of good news you received", cues: ["what the news was", "when you received it", "who told you", "why it mattered to you"], part3: ["Why do people like sharing good news?", "Has social media changed how news spreads?", "Should news organisations report more positive stories?", "Why can the same news affect people differently?"] },
  { id: "creative-person", category: "People", part2: "Describe a creative person you admire", cues: ["who the person is", "how you know about them", "what they have created", "why you admire their creativity"], part3: ["Can creativity be taught?", "How should schools encourage creative thinking?", "Does technology make people more or less creative?", "Why do societies need creative people?"] },
  { id: "busy-place", category: "Places", part2: "Describe a crowded place you have been to", cues: ["where it was", "when you went there", "why it was crowded", "how you felt there"], part3: ["Why are cities becoming more crowded?", "What problems does overcrowding create?", "Do people behave differently in crowds?", "How can public spaces be designed better?"] },
  { id: "difficult-decision", category: "Experiences", part2: "Describe a difficult decision that had a good result", cues: ["what the decision was", "why it was difficult", "how you made it", "why the result was positive"], part3: ["Why do some people find decisions difficult?", "Should young people make important decisions alone?", "How much should emotions influence decisions?", "Are quick decisions sometimes better?"] },
  { id: "useful-website", category: "Technology", part2: "Describe a website or app that you find useful", cues: ["what it is", "how often you use it", "what you use it for", "why you find it useful"], part3: ["How have apps changed daily life?", "Should children have unrestricted internet access?", "Why do some digital services become addictive?", "What responsibilities do technology companies have?"] },
  { id: "important-rule", category: "Society", part2: "Describe an important rule at your school or workplace", cues: ["what the rule is", "why it exists", "how people respond to it", "why you think it is important"], part3: ["Why does society need rules?", "What makes a rule effective?", "Should the same rules apply to everyone?", "When is it acceptable to challenge a rule?"] },
  { id: "enjoyed-meal", category: "Things", part2: "Describe a meal that you really enjoyed with other people", cues: ["what you ate", "who you were with", "where you had the meal", "why you remember it"], part3: ["Why are shared meals important?", "How are eating habits changing?", "Should traditional food be protected?", "Why is convenience food so popular?"] }
];
