// IELTS SPEAKING TOPIC POOL
// Add another t(...) line before the closing ]; to create a new topic.
// Format: t("unique-id", "Category", "Part 2 question", [four cue points], [four Part 3 questions])

const t = (id, category, part2, cues, part3) => ({ id, category, part2, cues, part3 });

const topics = [
  // Original demonstration cards
  t("helpful-person", "People", "Describe a person who has helped you achieve a goal", ["who this person is", "what goal you wanted to achieve", "how they helped you", "how you felt about their help"], ["Why do people set goals?", "Should parents help children set goals?", "Is teamwork always helpful when pursuing a goal?", "What makes someone a good mentor?"]),
  t("interesting-place", "Places", "Describe an interesting place you would like to visit", ["where it is", "how you learned about it", "what you would do there", "why you find it interesting"], ["Why do people enjoy visiting unfamiliar places?", "How can tourism change a local community?", "Should famous places limit visitor numbers?", "Will virtual travel ever replace physical travel?"]),
  t("skill-learned", "Experiences", "Describe a useful skill you learned outside school", ["what the skill is", "when and how you learned it", "how difficult it was", "why it is useful to you"], ["Which skills should schools teach?", "Do people learn better alone or with others?", "Why do some adults stop learning new skills?", "How has technology changed the way people learn?"]),
  t("object-kept", "Things & Media", "Describe an old object that your family has kept for a long time", ["what it is", "where it came from", "how long your family has had it", "why it is important"], ["Why do people keep old objects?", "Are museums still important today?", "What kinds of objects represent a culture?", "Will digital records replace physical keepsakes?"]),
  t("nature-place", "Nature", "Describe a natural place where you feel relaxed", ["where it is", "what it looks like", "what you do there", "why it helps you relax"], ["Why is access to nature important in cities?", "Who should pay to protect natural areas?", "How can tourism harm the environment?", "Do young people care enough about nature?"]),
  t("good-news", "Experiences", "Describe a piece of good news you received", ["what the news was", "when you received it", "who told you", "why it mattered to you"], ["Why do people like sharing good news?", "Has social media changed how news spreads?", "Should news organisations report more positive stories?", "Why can the same news affect people differently?"]),
  t("creative-person", "People", "Describe a creative person you admire", ["who the person is", "how you know about them", "what they have created", "why you admire their creativity"], ["Can creativity be taught?", "How should schools encourage creative thinking?", "Does technology make people more or less creative?", "Why do societies need creative people?"]),
  t("busy-place", "Places", "Describe a crowded place you have been to", ["where it was", "when you went there", "why it was crowded", "how you felt there"], ["Why are cities becoming more crowded?", "What problems does overcrowding create?", "Do people behave differently in crowds?", "How can public spaces be designed better?"]),
  t("difficult-decision", "Experiences", "Describe a difficult decision that had a good result", ["what the decision was", "why it was difficult", "how you made it", "why the result was positive"], ["Why do some people find decisions difficult?", "Should young people make important decisions alone?", "How much should emotions influence decisions?", "Are quick decisions sometimes better?"]),
  t("useful-website", "Technology & Work", "Describe a website or app that you find useful", ["what it is", "how often you use it", "what you use it for", "why you find it useful"], ["How have apps changed daily life?", "Should children have unrestricted internet access?", "Why do some digital services become addictive?", "What responsibilities do technology companies have?"]),
  t("important-rule", "Society & Culture", "Describe an important rule at your school or workplace", ["what the rule is", "why it exists", "how people respond to it", "why you think it is important"], ["Why does society need rules?", "What makes a rule effective?", "Should the same rules apply to everyone?", "When is it acceptable to challenge a rule?"]),
  t("enjoyed-meal", "Things & Media", "Describe a meal that you really enjoyed with other people", ["what you ate", "who you were with", "where you had the meal", "why you remember it"], ["Why are shared meals important?", "How are eating habits changing?", "Should traditional food be protected?", "Why is convenience food so popular?"]),

  // People — 12 new cards
  t("hardworking-person", "People", "Describe a hardworking person you know", ["who the person is", "what work they do", "what makes them hardworking", "what you have learned from them"], ["Why do some people work harder than others?", "Should employers reward effort or results?", "Can working too hard be harmful?", "How may attitudes to work change in the future?"]),
  t("polite-person", "People", "Describe a person you know who is very polite", ["who they are", "how you know them", "how they show politeness", "why their behaviour stands out"], ["Are standards of politeness changing?", "Should schools teach manners?", "Does politeness mean the same thing across cultures?", "Can someone be too polite?"]),
  t("interesting-older-person", "People", "Describe an interesting older person you have met", ["who the person is", "where you met", "what you talked about", "why you found them interesting"], ["What can younger people learn from older people?", "Why do generations sometimes misunderstand each other?", "Should older people continue working?", "How can communities reduce loneliness among the elderly?"]),
  t("clever-child", "People", "Describe a child who impressed you", ["who the child is", "where you met them", "what they did", "why you were impressed"], ["What does it mean for a child to be talented?", "Should talented children receive special education?", "How much pressure should parents place on children?", "Can childhood talent predict adult success?"]),
  t("family-member-admire", "People", "Describe a family member you admire", ["who they are", "what they are like", "what they have done", "why you admire them"], ["How have family roles changed?", "Who influences children most within a family?", "Is living near relatives still important?", "What makes family relationships strong?"]),
  t("memorable-teacher", "People", "Describe a teacher who had a positive influence on you", ["who the teacher was", "what they taught", "what made their teaching special", "how they influenced you"], ["What qualities make an effective teacher?", "Can technology replace some roles of teachers?", "Should students evaluate their teachers?", "Why do some teachers remain memorable for life?"]),
  t("different-culture-person", "People", "Describe someone from a different culture whom you enjoy spending time with", ["who the person is", "how you met", "what you do together", "what you have learned from them"], ["What are the benefits of multicultural communities?", "Why can cultural misunderstandings occur?", "Should migrants adapt completely to a new culture?", "How can schools encourage cultural understanding?"]),
  t("musician-like", "People", "Describe a musician or singer whose work you enjoy", ["who they are", "how you discovered them", "what kind of music they make", "why you enjoy their work"], ["Why is music important in society?", "How has streaming changed musicians' careers?", "Should music education be compulsory?", "Why do musical tastes differ between generations?"]),
  t("sportsperson-admire", "People", "Describe a sportsperson you admire", ["who the person is", "what sport they play", "what they have achieved", "why you admire them"], ["Why do societies admire athletes?", "Are professional athletes paid too much?", "Should athletes be role models?", "How can countries encourage more people to play sport?"]),
  t("businessperson-admire", "People", "Describe a businessperson you find interesting", ["who they are", "what business they are involved in", "how you learned about them", "why you find them interesting"], ["What qualities are needed to run a business?", "Should businesses focus mainly on profit?", "Why do many new businesses fail?", "Will small businesses survive against large companies?"]),
  t("good-neighbour", "People", "Describe a neighbour you get along with well", ["who the person is", "how often you meet", "what you do for each other", "why you value this neighbour"], ["Why do some neighbours rarely speak?", "Are neighbours more important in villages or cities?", "How can neighbourhoods build trust?", "Should people be responsible for helping nearby residents?"]),
  t("friend-reconnected", "People", "Describe a friend you contacted again after a long time", ["who the friend is", "why you lost contact", "how you reconnected", "how you felt about meeting again"], ["Why do friendships sometimes fade?", "Has social media improved friendship?", "Are childhood friendships different from adult friendships?", "What qualities help a friendship last?"]),

  // Places — 12 new cards
  t("historical-building", "Places", "Describe a historical building you have visited", ["where it is", "what it looks like", "what you learned there", "why it was memorable"], ["Why should historic buildings be preserved?", "Who should pay for their maintenance?", "Can old buildings be adapted for modern use?", "Why are some people uninterested in history?"]),
  t("quiet-place", "Places", "Describe a quiet place you like to spend time in", ["where it is", "when you go there", "what you do there", "why you like its atmosphere"], ["Why is silence difficult to find in cities?", "Do people need quiet time every day?", "How does noise affect health?", "Should governments regulate urban noise more strictly?"]),
  t("noisy-place", "Places", "Describe a noisy place you have visited", ["where it was", "what caused the noise", "what you did there", "how you felt about it"], ["What are the main sources of noise pollution?", "Why do some people enjoy noisy environments?", "Should public transport have quiet areas?", "Will cities become noisier in the future?"]),
  t("local-shop", "Places", "Describe a local shop that you often visit", ["where it is", "what it sells", "how often you go", "why you like shopping there"], ["Why are local shops disappearing?", "What advantages do large shopping centres offer?", "How has online shopping changed town centres?", "Should governments support small retailers?"]),
  t("restaurant-recommend", "Places", "Describe a restaurant you would recommend", ["where it is", "what food it serves", "who you went with", "why you recommend it"], ["Why do people enjoy eating outside the home?", "What makes a restaurant successful?", "Should restaurants display nutritional information?", "How may restaurants change in the future?"]),
  t("public-park", "Places", "Describe a public park or garden you enjoy visiting", ["where it is", "what it looks like", "what people do there", "why you enjoy it"], ["Why do cities need public parks?", "How should parks be funded?", "Should parks prioritise nature or recreation?", "How can parks be made safer and more inclusive?"]),
  t("city-live", "Places", "Describe a city where you would like to live for a short time", ["which city it is", "how you know about it", "what you would do there", "why you would like to live there"], ["Why do people move to large cities?", "What makes a city pleasant to live in?", "Should governments limit urban growth?", "Will remote work reduce migration to cities?"]),
  t("rural-place", "Places", "Describe a rural place you have enjoyed visiting", ["where it is", "when you went", "what you saw or did", "why you enjoyed the visit"], ["Why are rural populations declining?", "What services should villages provide?", "Is rural tourism beneficial?", "How can technology improve life in remote areas?"]),
  t("comfortable-home", "Places", "Describe a home that you think is particularly comfortable", ["whose home it is", "where it is", "what it is like inside", "why it feels comfortable"], ["What makes a home comfortable?", "How have homes changed in recent decades?", "Is owning a home important?", "How might people live differently in the future?"]),
  t("school-place", "Places", "Describe a place at your school or university that you remember well", ["where it was", "what it looked like", "what happened there", "why you remember it"], ["How does school design affect learning?", "Should students help design learning spaces?", "Do schools need more outdoor areas?", "Will physical classrooms remain necessary?"]),
  t("library-visited", "Places", "Describe a library you have visited", ["where it is", "what it is like", "what you did there", "why the visit was useful"], ["Are libraries still necessary in the digital age?", "What services should modern libraries provide?", "How can children be encouraged to use libraries?", "Should libraries be completely free?"]),
  t("street-market", "Places", "Describe a market you enjoyed visiting", ["where it was", "what was sold there", "who you went with", "why you enjoyed it"], ["Why do traditional markets remain popular?", "How are markets different from supermarkets?", "Should street markets be regulated?", "Can markets help preserve local culture?"]),

  // Experiences and events — 12 new cards
  t("time-late", "Experiences", "Describe a time when you were late for something important", ["what you were late for", "why you were late", "what happened", "how you felt afterwards"], ["Why are some people frequently late?", "Is punctuality equally important in every culture?", "How can organisations handle lateness fairly?", "Has technology made people more punctual?"]),
  t("promise-kept", "Experiences", "Describe a promise you made and kept", ["what you promised", "who you made the promise to", "how you kept it", "why it mattered"], ["Why are promises important?", "Why do people sometimes break promises?", "Should promises between friends be taken seriously?", "Are written agreements more trustworthy than spoken ones?"]),
  t("difficult-challenge", "Experiences", "Describe a difficult challenge that you completed", ["what the challenge was", "why it was difficult", "what you did", "what you learned from it"], ["Why do people voluntarily take on challenges?", "Should children be protected from failure?", "What helps people remain persistent?", "Are physical and mental challenges equally valuable?"]),
  t("pleasant-surprise", "Experiences", "Describe a pleasant surprise you experienced", ["what happened", "when and where it happened", "who was involved", "why it surprised you"], ["Why do people enjoy surprises?", "Are planned celebrations better than surprises?", "How do companies use surprise in marketing?", "Can unexpected events improve people's adaptability?"]),
  t("family-celebration", "Experiences", "Describe a family celebration you remember well", ["what was celebrated", "where it took place", "who attended", "why you remember it"], ["Why are family celebrations important?", "How have celebrations changed?", "Do large celebrations create unnecessary expense?", "Will families celebrate more online in the future?"]),
  t("memorable-journey", "Experiences", "Describe a memorable journey you made", ["where you went", "how you travelled", "who was with you", "why the journey was memorable"], ["Why do people remember some journeys clearly?", "How has transport changed travel experiences?", "Should long-distance travel be discouraged for environmental reasons?", "What might transport look like in the future?"]),
  t("lost-important-item", "Experiences", "Describe a time when you lost something important", ["what you lost", "where and when it happened", "what you did to find it", "how the situation ended"], ["Why do people lose possessions?", "Has technology made lost items easier to recover?", "Should finders always receive a reward?", "Why are people emotionally attached to objects?"]),
  t("made-complaint", "Experiences", "Describe a time when you made a complaint and received a useful response", ["what the problem was", "who you complained to", "what you said", "how the problem was resolved"], ["Why are some people reluctant to complain?", "What makes complaint handling effective?", "Are online reviews fair to businesses?", "Should consumers receive stronger legal protection?"]),
  t("good-service", "Experiences", "Describe a time when you received excellent service", ["where it happened", "what service you needed", "what the staff did", "why the service impressed you"], ["What does good customer service involve?", "Should service workers receive more training?", "Will machines replace customer-service staff?", "Why do expectations of service differ between people?"]),
  t("waited-special", "Experiences", "Describe a time when you waited a long time for something special", ["what you waited for", "how long you waited", "what you did while waiting", "why it was worth the wait"], ["Why are people becoming less patient?", "Where do people commonly have to wait?", "How can organisations reduce waiting times?", "Is patience still an important quality?"]),
  t("taught-someone", "Experiences", "Describe a time when you taught someone how to do something", ["who you taught", "what you taught them", "how you explained it", "how you felt about the result"], ["What makes someone good at teaching?", "Do people learn better from experts or friends?", "How has online video changed informal learning?", "Should everyone learn how to teach others?"]),
  t("positive-risk", "Experiences", "Describe a time when you took a risk that had a positive result", ["what the risk was", "why you took it", "what happened", "what you learned"], ["Why are some people more willing to take risks?", "Should teenagers be encouraged to take risks?", "How do businesses assess risk?", "Can avoiding all risk be harmful?"]),

  // Things, art and media — 12 new cards
  t("meaningful-photo", "Things & Media", "Describe a photograph that is important to you", ["what the photograph shows", "when it was taken", "where you keep it", "why it matters to you"], ["Why do people take so many photographs?", "Are digital photographs less meaningful?", "When is taking photographs inappropriate?", "How can photographs influence public opinion?"]),
  t("memorable-gift", "Things & Media", "Describe a gift that you remember receiving", ["what it was", "who gave it to you", "when you received it", "why you remember it"], ["Why do people give gifts?", "Are expensive gifts more meaningful?", "How does advertising influence gift buying?", "Is giving experiences better than giving objects?"]),
  t("favourite-clothing", "Things & Media", "Describe an item of clothing that you enjoy wearing", ["what it is", "where you got it", "when you wear it", "why you like it"], ["Why do fashions change quickly?", "How does clothing express identity?", "Should schools or workplaces require uniforms?", "How can the clothing industry become more sustainable?"]),
  t("childhood-toy", "Things & Media", "Describe a toy you enjoyed as a child", ["what it was", "who gave it to you", "how you played with it", "why you remember it"], ["How have children's toys changed?", "Do children need many toys?", "Are digital games replacing traditional toys?", "What can children learn through play?"]),
  t("book-film", "Things & Media", "Describe a book that was made into a film", ["what the book was", "what the story was about", "what the film was like", "which version you preferred"], ["Why are popular books adapted into films?", "Why do films often change the original story?", "Can films encourage people to read?", "Will visual media reduce book reading?"]),
  t("film-recommend", "Things & Media", "Describe a film you would recommend to others", ["what the film is", "what it is about", "when you watched it", "why you recommend it"], ["What makes a film successful?", "Should films mainly entertain or educate?", "How have streaming services changed cinema?", "Do films influence social attitudes?"]),
  t("song-memory", "Things & Media", "Describe a song that brings back a strong memory", ["what the song is", "when you first heard it", "what memory it brings back", "why it affects you"], ["Why is music connected to memory?", "How does music shape cultural identity?", "Why do songs become popular?", "Will computer-generated music become common?"]),
  t("effective-advertisement", "Things & Media", "Describe an advertisement that you remember clearly", ["what it advertised", "where you saw it", "what it was like", "why you remember it"], ["How strongly does advertising influence consumers?", "Should advertising to children be restricted?", "Why do companies use famous people in advertisements?", "How will advertising change with artificial intelligence?"]),
  t("useful-equipment", "Things & Media", "Describe a piece of equipment that is useful in your home", ["what it is", "how often you use it", "what it does", "why it is useful"], ["How have household appliances changed family life?", "Why do people replace working equipment?", "Should products be easier to repair?", "Will homes become fully automated?"]),
  t("bag-use", "Things & Media", "Describe a bag that you use regularly", ["what it looks like", "when you got it", "what you carry in it", "why it suits your needs"], ["Why do people carry so many possessions?", "How important are brands when buying accessories?", "Should plastic bags be banned?", "How can everyday products be designed sustainably?"]),
  t("work-of-art", "Things & Media", "Describe a work of art that you like", ["what it is", "where you saw it", "what it shows", "why you like it"], ["What role does art play in society?", "Should governments fund the arts?", "How can children benefit from art education?", "Can digital work be considered fine art?"]),
  t("useful-invention", "Things & Media", "Describe an invention that has improved people's lives", ["what it is", "when it became widely used", "how people use it", "why it is important"], ["What encourages people to invent things?", "Should inventors be responsible for harmful uses?", "Which inventions have changed society most?", "What problems should future inventions address?"]),

  // Activities — 12 new cards
  t("sport-enjoy", "Activities", "Describe a sport that you enjoy playing or watching", ["what the sport is", "how you became interested", "when you play or watch it", "why you enjoy it"], ["Why are some sports more popular than others?", "Should everyone take part in competitive sport?", "How does sport bring communities together?", "Will electronic sports become as important as physical sports?"]),
  t("outdoor-activity", "Activities", "Describe an outdoor activity you would like to try", ["what it is", "where it can be done", "who you would do it with", "why you want to try it"], ["Why are outdoor activities important?", "What prevents people from spending time outdoors?", "Should risky activities be regulated?", "How can cities encourage outdoor recreation?"]),
  t("indoor-activity", "Activities", "Describe an indoor activity you enjoy", ["what it is", "where you do it", "who you do it with", "why it is enjoyable"], ["Why do people spend more time indoors now?", "Are indoor hobbies less healthy?", "How can indoor activities connect people?", "Will virtual activities replace physical ones?"]),
  t("relaxing-hobby", "Activities", "Describe a hobby that helps you relax", ["what the hobby is", "how you started it", "how often you do it", "why it relaxes you"], ["Why do adults need hobbies?", "Should hobbies be productive?", "Why do some hobbies become expensive?", "How might leisure time change in the future?"]),
  t("group-activity", "Activities", "Describe a group activity that you enjoyed", ["what the activity was", "who took part", "what your role was", "why you enjoyed it"], ["What makes teamwork effective?", "Why do some people dislike group activities?", "Should schools assess group work?", "How does remote collaboration differ from working together in person?"]),
  t("water-activity", "Activities", "Describe an activity you have done in or near water", ["what the activity was", "where you did it", "who was with you", "how you felt"], ["Why are water activities popular?", "Should swimming be taught to every child?", "How can water sports affect the environment?", "What responsibilities do authorities have for water safety?"]),
  t("healthy-exercise", "Activities", "Describe a form of exercise that you think is good for health", ["what it is", "where it can be done", "how often people should do it", "why it is beneficial"], ["Why do many people avoid exercise?", "Should employers support workers' fitness?", "Is public money better spent on sports facilities or healthcare?", "How has technology affected physical activity?"]),
  t("concentration-activity", "Activities", "Describe an activity that requires strong concentration", ["what the activity is", "when you do it", "why concentration is needed", "how you stay focused"], ["Why is concentration difficult for many people?", "Do digital devices reduce attention spans?", "How can schools help students focus?", "Are frequent breaks helpful for productivity?"]),
  t("cooking-activity", "Activities", "Describe something you learned to cook", ["what the dish is", "who taught you", "how it is prepared", "why you wanted to learn it"], ["Should all children learn to cook?", "Why are traditional recipes important?", "How has convenience food changed cooking skills?", "Will people cook less in the future?"]),
  t("shopping-experience", "Activities", "Describe a shopping experience that you enjoyed", ["where you shopped", "what you were looking for", "who you were with", "why you enjoyed it"], ["Why do some people enjoy shopping?", "How is online shopping changing consumer behaviour?", "Should shops be open all night?", "What makes people buy things they do not need?"]),
  t("volunteer-activity", "Activities", "Describe a volunteering activity you would like to take part in", ["what the activity is", "who it would help", "what you would do", "why you want to participate"], ["Why do people volunteer?", "Should students be required to do community service?", "How can charities attract more volunteers?", "Should volunteers replace paid workers?"]),
  t("skill-want-learn", "Activities", "Describe a practical skill you would like to learn", ["what the skill is", "why you want to learn it", "how you could learn it", "how it would help you"], ["Which practical skills are most important today?", "Why have some traditional skills disappeared?", "Should vocational training receive more respect?", "Will technology reduce the need for practical skills?"]),

  // Nature and environment — 12 new cards
  t("interesting-animal", "Nature", "Describe an animal that you find interesting", ["what it is", "where it lives", "when you first learned about it", "why it interests you"], ["Why are some animals endangered?", "Should governments spend more on wildlife protection?", "What are the advantages and disadvantages of zoos?", "How can ordinary people help wild animals?"]),
  t("important-plant", "Nature", "Describe a plant that is important in your country", ["what the plant is", "where it grows", "how people use it", "why it is important"], ["Why should plant species be protected?", "How does urban development affect plants?", "Should schools teach gardening?", "How might climate change affect agriculture?"]),
  t("garden-like", "Nature", "Describe a garden that you like", ["where it is", "what grows there", "when you visit", "why you like it"], ["Why do people enjoy gardening?", "Should cities provide community gardens?", "Can gardening improve health?", "How can gardens support wildlife?"]),
  t("beautiful-sky", "Nature", "Describe a time when you saw a beautiful sky", ["where you were", "what the sky looked like", "who you were with", "how it made you feel"], ["Why are people fascinated by the sky?", "How does light pollution affect society?", "Should cities reduce unnecessary lighting?", "Why is space exploration important?"]),
  t("perfect-weather", "Nature", "Describe a day when the weather was perfect", ["when it was", "what the weather was like", "what you did", "why you enjoyed it"], ["How does weather affect mood?", "Why do weather preferences differ?", "How does extreme weather affect a country?", "Can people adapt successfully to climate change?"]),
  t("water-place", "Nature", "Describe a place near water that you enjoyed visiting", ["where it is", "what kind of water is there", "what you did", "why you enjoyed the place"], ["Why do many people choose to live near water?", "How can water pollution be reduced?", "Should access to beaches and rivers be free?", "How might rising sea levels affect communities?"]),
  t("environmental-problem", "Nature", "Describe an environmental problem in a place you know", ["what the problem is", "where it occurs", "what causes it", "what could be done"], ["Who is most responsible for environmental protection?", "Why is it difficult to change environmental behaviour?", "Should companies face stricter environmental penalties?", "Can economic growth and environmental protection coexist?"]),
  t("environmental-law", "Nature", "Describe an environmental law you would like to introduce", ["what the law would require", "who it would affect", "how it would be enforced", "why it is needed"], ["Why do environmental laws sometimes fail?", "Should individuals or companies bear more responsibility?", "How can governments gain public support for green policies?", "Are international environmental agreements effective?"]),
  t("favourite-season", "Nature", "Describe your favourite season of the year", ["which season it is", "what the weather is like", "what you usually do", "why it is your favourite"], ["How do seasons affect people's lifestyles?", "Why are seasonal traditions important?", "How does climate affect national culture?", "Will climate change alter the way people think about seasons?"]),
  t("farm-visited", "Nature", "Describe a farm you have visited or would like to visit", ["where it is", "what is produced there", "what you did or would do", "why it interests you"], ["Why are fewer people becoming farmers?", "Should governments support small farms?", "How is technology changing agriculture?", "Is organic farming sustainable on a large scale?"]),
  t("natural-sound", "Nature", "Describe a sound from nature that you enjoy", ["what the sound is", "where you hear it", "when you usually hear it", "why you enjoy it"], ["Why can natural sounds reduce stress?", "How does urban noise affect people?", "Should quiet natural areas be protected?", "Can recordings provide the same benefit as real nature?"]),
  t("endangered-species", "Nature", "Describe an endangered animal you would like to protect", ["what the animal is", "where it lives", "why it is endangered", "why you want to protect it"], ["Why should humans protect endangered species?", "Which conservation methods work best?", "Should local people be compensated for protecting wildlife?", "Is it ever acceptable to prioritise people over animals?"]),

  // Technology, education and work — 12 new cards
  t("useful-device", "Technology & Work", "Describe a technological device you use often", ["what it is", "when you got it", "what you use it for", "why it is useful"], ["Why do people replace devices so frequently?", "Does technology make life simpler?", "How can electronic waste be reduced?", "Which devices may disappear in the future?"]),
  t("educational-app", "Technology & Work", "Describe an app that helped you learn something", ["what the app is", "how you found it", "what you learned", "why it was effective"], ["What are the weaknesses of learning through apps?", "Should schools recommend commercial apps?", "Why do older people sometimes struggle with apps?", "How will educational technology develop?"]),
  t("online-course", "Technology & Work", "Describe an online course or lesson that you found useful", ["what it was about", "when you took it", "how it was taught", "why it was useful"], ["Can online learning replace classrooms?", "What makes an online course effective?", "Should university education be available online for free?", "How does online learning affect social skills?"]),
  t("science-subject", "Technology & Work", "Describe an area of science that interests you", ["what it is", "how you became interested", "what you know about it", "why it matters"], ["Why should everyone understand basic science?", "How can schools make science more engaging?", "Should governments fund research without immediate benefits?", "What responsibilities do scientists have to society?"]),
  t("useful-lesson", "Technology & Work", "Describe an important lesson you learned at school", ["what the lesson was", "who taught it", "how you learned it", "why it remains important"], ["What should the main purpose of school be?", "Are examinations a fair way to assess students?", "Which life skills belong in the curriculum?", "How will education change over the next twenty years?"]),
  t("team-project", "Technology & Work", "Describe a project you completed with other people", ["what the project was", "who worked with you", "what your responsibility was", "why the project was successful or difficult"], ["Why do workplaces use teams?", "How should work be divided in a team?", "What causes conflict between colleagues?", "Can online teams be as effective as face-to-face teams?"]),
  t("important-job", "Technology & Work", "Describe a job that you think is important to society", ["what the job is", "what the work involves", "what skills are needed", "why it is important"], ["Why are some important jobs poorly paid?", "How should young people choose careers?", "Which jobs are most likely to be automated?", "Should governments guarantee employment?"]),
  t("successful-company", "Technology & Work", "Describe a successful company you know about", ["what the company is", "what it provides", "how you learned about it", "why you think it is successful"], ["How should business success be measured?", "What responsibilities do large companies have?", "Why do consumers trust some brands?", "Will global companies become more powerful?"]),
  t("work-team", "Technology & Work", "Describe a team you enjoyed being part of", ["what the team did", "who was in it", "what your role was", "why you enjoyed the experience"], ["What qualities make a good team leader?", "Should teams make decisions democratically?", "How can managers motivate a team?", "Are individual rewards harmful to teamwork?"]),
  t("presentation-gave", "Technology & Work", "Describe a presentation or talk that you gave", ["what it was about", "who listened", "how you prepared", "how you felt about it"], ["Why are public-speaking skills valuable?", "Should schools require presentations?", "What makes a speaker persuasive?", "Has technology improved presentations?"]),
  t("helpful-website-learning", "Technology & Work", "Describe a website that you use for study or work", ["what the website is", "how you discovered it", "what it helps you do", "why you trust it"], ["How can people judge information online?", "Should useful knowledge be free on the internet?", "Why do websites collect user data?", "How might the web change in the future?"]),
  t("ai-tool", "Technology & Work", "Describe an artificial-intelligence tool you have used or would like to use", ["what the tool is", "what it can do", "how you use or would use it", "why it interests you"], ["How might artificial intelligence change employment?", "Should students be allowed to use AI tools?", "Who is responsible when AI makes a mistake?", "What limits should society place on AI?"]),

  // Society and culture — 12 new cards
  t("special-festival", "Society & Culture", "Describe a festival or special public event that you enjoyed", ["what the event was", "where it took place", "what happened", "why you enjoyed it"], ["Why are festivals important to communities?", "How does tourism affect traditional festivals?", "Should public money fund celebrations?", "Can festivals survive if young people lose interest?"]),
  t("family-tradition", "Society & Culture", "Describe a tradition followed by your family or community", ["what the tradition is", "when it is followed", "what people do", "why it is meaningful"], ["Why do traditions change?", "Should harmful traditions be abandoned?", "How can traditions strengthen identity?", "Will globalisation make cultures more similar?"]),
  t("law-admire", "Society & Culture", "Describe a law in your country that you think is beneficial", ["what the law is", "when you learned about it", "who it protects or affects", "why you support it"], ["What makes people obey laws?", "Should laws reflect moral values?", "Why do laws differ between countries?", "How should outdated laws be changed?"]),
  t("public-rule-change", "Society & Culture", "Describe a public rule that you would like to change", ["what the rule is", "where it applies", "why you disagree with it", "what you would replace it with"], ["Why are some rules unpopular?", "How should governments consult the public?", "Is strict enforcement always effective?", "When should individual freedom be limited?"]),
  t("public-service", "Society & Culture", "Describe a public service that is useful in your area", ["what the service is", "who uses it", "how it helps people", "how it could be improved"], ["Which public services deserve the most funding?", "Should some public services charge fees?", "How can governments measure service quality?", "Can private companies provide public services better?"]),
  t("public-transport-trip", "Society & Culture", "Describe a journey you made using public transport", ["where you travelled", "which form of transport you used", "what happened during the journey", "how you felt about it"], ["Why do people prefer private cars?", "How can public transport attract more users?", "Should city-centre driving be restricted?", "What transport innovations will matter most?"]),
  t("important-news-story", "Society & Culture", "Describe a news story that interested you", ["what the story was", "where you heard about it", "why it interested you", "what you learned from it"], ["How can people identify reliable news?", "Should news organisations remain politically neutral?", "Why does negative news attract attention?", "How has social media changed journalism?"]),
  t("famous-person-country", "Society & Culture", "Describe a famous person from your country", ["who the person is", "what they are known for", "how people view them", "why you chose them"], ["Why do societies create celebrities?", "Do famous people deserve privacy?", "Should celebrities use their influence for social causes?", "How has the meaning of fame changed?"]),
  t("language-learn", "Society & Culture", "Describe a language other than English that you would like to learn", ["which language it is", "where it is spoken", "how you would learn it", "why you want to learn it"], ["Why do some languages disappear?", "Should everyone learn an international language?", "How does language shape identity?", "Will translation technology reduce language learning?"]),
  t("traditional-food", "Society & Culture", "Describe a traditional food from your culture", ["what it is", "how it is prepared", "when people eat it", "why it is culturally important"], ["Why should traditional food be preserved?", "How does migration change national cuisine?", "Should governments regulate unhealthy food?", "Will diets become more similar worldwide?"]),
  t("community-change", "Society & Culture", "Describe a positive change in your local community", ["what changed", "when it happened", "who was responsible", "how local people benefited"], ["Why do communities resist change?", "How can residents influence local decisions?", "Should cities prioritise economic growth or quality of life?", "What makes a community feel connected?"]),
  t("successful-public-event", "Society & Culture", "Describe a public event that was organised successfully", ["what the event was", "where and when it happened", "how it was organised", "why it was successful"], ["What skills are needed to organise large events?", "How do public events benefit cities?", "Should events be cancelled for environmental reasons?", "How can organisers keep crowds safe?"])
];
